### ISSUE TITLE
Port to Vercel

### ISSUE THREAD

**Issue by seveibar** [mshick/add-pr-comment-bot#9]
We should have a vercel-compatible version of this

**Comment by algora-pbc** [comment]
💎 **seveibar** is offering a **$20** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #9` in the PR body and joining algora.io

**Comment by seveibar** [comment]
hmm sorry i think the bounty could only be done if we merged upstream to this repo, which would change it's simplicity, we should create a fork
